#!/bin/bash
# Make releases

VER=2.3.4
LVER=${VER}.LGPL
BIN=MathGL
LBIN=MathGL-LGPL
WBIN=MathGL-Win10
SRC=/home/balakin/mathgl-code/mathgl-2x
BSRC=${SRC}/build
GPL=mathgl-${VER}-mingw.i686
LGPL=mathgl-${VER}.LGPL-mingw.i386
WIN8=mathgl-${VER}.Win10-mingw.i386
EXE=mgl_scripts-${VER}
EXE8=mgl_scripts-${VER}.Win10

mkdir ${GPL}
mkdir ${GPL}/bin/
cp -p ${BIN}/bin/* ${GPL}/bin/
mkdir ${GPL}/lib/
cp -p ${BIN}/lib/* ${GPL}/lib/
mkdir ${GPL}/include/
mkdir ${GPL}/include/mgl2/
cp -p ${BIN}/include/mgl2/* ${GPL}/include/mgl2/
cp -p ${SRC}/ChangeLog.txt ${GPL}/
cp -p ${SRC}/FindMathGL2.cmake ${GPL}/mathgl2-config.cmake
7z a ${GPL}.7z ${GPL}/
rm -R ${GPL}

mkdir ${WIN8}
mkdir ${WIN8}/bin/
cp -p ${WBIN}/bin/* ${WIN8}/bin/
mkdir ${WIN8}/lib/
cp -p ${WBIN}/lib/* ${WIN8}/lib/
mkdir ${WIN8}/include/
mkdir ${WIN8}/include/mgl2/
cp -p ${WBIN}/include/mgl2/* ${WIN8}/include/mgl2/
cp -p ${SRC}/ChangeLog.txt ${WIN8}/
cp -p ${SRC}/FindMathGL2.cmake ${WIN8}/mathgl2-config.cmake
7z a ${WIN8}.7z ${WIN8}/
rm -R ${WIN8}

mkdir ${LGPL}
mkdir ${LGPL}/bin/
cp -p ${LBIN}/bin/* ${LGPL}/bin/
mkdir ${GPL}/lib/
cp -p ${LBIN}/lib/* ${LGPL}/lib/
mkdir ${LGPL}/include/
mkdir ${LGPL}/include/mgl2/
cp -p ${LBIN}/include/mgl2/* ${LGPL}/include/mgl2/
cp -p ${SRC}/ChangeLog.txt ${LGPL}/
cp -p ${SRC}/FindMathGL2.cmake ${LGPL}/mathgl2-config.cmake
7z a ${LGPL}.7z ${LGPL}/
rm -R ${LGPL}

mkdir ${EXE}
cp -pR ${BIN}/extra/* ${EXE}/
cp -p ${BIN}/bin/* ${EXE}/
cp -p ${BIN}/share/mathgl/mgl.cgi.exe ${EXE}/
cp -p ${BIN}/share/udav/*.qm ${EXE}/
cp -p ${BSRC}/texinfo/mgl_??.html ${EXE}/
cp -p ${SRC}/ChangeLog.txt ${EXE}/
7z a ${EXE}.7z ${EXE}/
rm -R ${EXE}

mkdir ${EXE8}
cp -pR ${WBIN}/extra/* ${EXE8}/
cp -p ${WBIN}/bin/* ${EXE8}/
cp -p ${WBIN}/share/udav/*.qm ${EXE8}/
cp -p ${BSRC}/texinfo/mgl_??.html ${EXE8}/
cp -p ${SRC}/ChangeLog.txt ${EXE8}/
7z a ${EXE8}.7z ${EXE8}/
rm -R ${EXE8}

cp -p ${BSRC}/texinfo/mathgl_en.pdf mathgl-${VER}.eng.pdf
cp -p ${BSRC}/texinfo/mgl_en.pdf mgl-${VER}.eng.pdf
cp -p ${SRC}/ChangeLog.txt ChangeLog-${VER}.txt
7z a mathgl-doc-html-${VER}.7z ${BSRC}/texinfo/m*html ${BSRC}/texinfo/png/

svn checkout svn://svn.code.sf.net/p/mathgl/code/mathgl-2x/ mathgl-${VER}
cd mathgl-${VER}
./clean-svn
cd ..
tar -zcf mathgl-${VER}.tar.gz mathgl-${VER}/
rm -R mathgl-${VER}
