#!/bin/bash
# Make releases

VER=2.4
LVER=${VER}.LGPL
BIN32=MathGL2-w32
BIN64=MathGL2-w64
LBIN32=MathGL2-lgpl-w32
LBIN64=MathGL2-lgpl-w64
SRC=/home/balakin/mathgl-code/mathgl-2x
BSRC=${SRC}/build

GPL32=mathgl-${VER}-mingw.win32
LGPL32=mathgl-${VER}.LGPL-mingw.win32
GPL64=mathgl-${VER}-mingw.win64
LGPL64=mathgl-${VER}.LGPL-mingw.win64
EXE32=mgl_scripts-${VER}.win32
EXE64=mgl_scripts-${VER}.win64

mkdir ${GPL32}
mkdir ${GPL32}/bin/
cp -p ${BIN32}/bin/libmgl* ${GPL32}/bin/
cp -pR ${BIN32}/[slim]* ${GPL32}/
cp -p ${SRC}/ChangeLog.txt ${GPL32}/
7z a ${GPL32}.7z ${GPL32}/
rm -R ${GPL32}

mkdir ${LGPL32}
cp -pR ${LBIN32}/* ${LGPL32}/
cp -p ${SRC}/ChangeLog.txt ${LGPL32}/
7z a ${LGPL32}.7z ${LGPL32}/
rm -R ${LGPL32}

mkdir ${EXE32}
cp -pR ${BIN32}/bin/* ${EXE32}/
cp -p ${BIN32}/share/mathgl/mgl.cgi.exe ${EXE32}/
cp -p ${BIN32}/share/udav/*.qm ${EXE32}/
cp -p ${BSRC}/texinfo/mgl_??.html ${EXE32}/
cp -p ${SRC}/ChangeLog.txt ${EXE32}/
7z a ${EXE32}.7z ${EXE32}/
rm -R ${EXE32}

mkdir ${GPL64}
mkdir ${GPL64}/bin/
cp -p ${BIN64}/bin/libmgl* ${GPL64}/bin/
cp -pR ${BIN64}/[slim]* ${GPL64}/
cp -p ${SRC}/ChangeLog.txt ${GPL64}/
7z a ${GPL64}.7z ${GPL64}/
rm -R ${GPL64}

mkdir ${LGPL64}
cp -pR ${LBIN64}/* ${LGPL64}/
cp -p ${SRC}/ChangeLog.txt ${LGPL64}/
7z a ${LGPL64}.7z ${LGPL64}/
rm -R ${LGPL64}

mkdir ${EXE64}
cp -pR ${BIN64}/bin/* ${EXE64}/
cp -p ${BIN64}/share/mathgl/mgl.cgi.exe ${EXE64}/
cp -p ${BIN64}/share/udav/*.qm ${EXE64}/
cp -p ${BSRC}/texinfo/mgl_??.html ${EXE64}/
cp -p ${SRC}/ChangeLog.txt ${EXE64}/
7z a ${EXE64}.7z ${EXE64}/
rm -R ${EXE64}

cp -p ${BSRC}/texinfo/mathgl_en.pdf mathgl-${VER}.eng.pdf
cp -p ${BSRC}/texinfo/mgl_en.pdf mgl-${VER}.eng.pdf
cp -p ${SRC}/ChangeLog.txt ChangeLog-${VER}.txt
7z a mathgl-doc-html-${VER}.7z ${BSRC}/texinfo/m*html ${BSRC}/texinfo/png/

svn checkout svn://svn.code.sf.net/p/mathgl/code/mathgl-2x/ mathgl-${VER}
cd mathgl-${VER}
./clean-svn
rm make_release
cd ..
tar -zcf mathgl-${VER}.tar.gz mathgl-${VER}/
rm -R mathgl-${VER}
